baseURL = "https://tct-1209.github.io/AWS1/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "en"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "tranchautrinh.2004@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "AWS Internship Report - Tran Chau Trinh"
weight = 1
languageName = "English"
label = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "BÃ¡o cÃ¡o thá»±c táº­p AWS - Tráº§n ChÃ¢u Trinh"
weight = 2
languageName = "Tiáº¿ng Viá»‡t"
label = "Tiáº¿ng Viá»‡t"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

